[startup.ssh_init]
name = "bash"
running_delay = -1

[startup.ssh_init.args]
script = """
chmod 400 -R /etc/ssh/
mkdir -p /run/sshd
[ -d /root/.ssh/ ] || mkdir /root/.ssh
"""

[startup.sshd]
name = "core.system"
after = ["ssh_init"]
protected = true

[startup.sshd.args]
name = "/usr/sbin/sshd"
args = ["-e", "-D"]

[startup.setup]
name = "bash"
running_delay = -1
after = ["sshd"]

[startup.setup.args]
script = """
set -x
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
export HOME=/root
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
echo 'remove a record was added by zos that make our server slow, below is resolv.conf file contents'
cat /etc/resolv.conf
sed -i '/^nameserver 10./d' /etc/resolv.conf
locale-gen en_US.UTF-8
export LC_ALL=en_US.UTF-8
chown -R postgres.postgres /var/lib/postgresql/
chown -R postgres.postgres /var/log/postgresql
gpasswd -a postgres ssl-cert
chown root:ssl-cert  /etc/ssl/private/ssl-cert-snakeoil.key
chmod 640 /etc/ssl/private/ssl-cert-snakeoil.key
chown postgres:ssl-cert /etc/ssl/private
chown -R postgres /var/run/postgresql
chown -R postgres.postgres /etc/postgresql

service postgresql start
sudo -u postgres createuser taiga
sudo -u postgres createdb taiga -O taiga --encoding='utf-8' --locale=en_US.utf8 --template=template0

# Install dependencies and populate database
chown -R taiga:taiga /home/taiga
cd /home/taiga/taiga-back
sudo chmod +x /opt/bin/prepare_taiga.sh
su taiga -c 'bash /opt/bin/prepare_taiga.sh'

# Start rabbitmq-server and create user+vhost
chown -R rabbitmq:rabbitmq /etc/rabbitmq
chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/
chown -R rabbitmq:rabbitmq /var/log/rabbitmq/
service rabbitmq-server start
rabbitmqctl add_user taiga $SECRET_KEY
rabbitmqctl add_vhost taiga
rabbitmqctl set_permissions -p taiga taiga '.*' '.*' '.*'

# edit backend
sed -i \"s|http://localhost/static/|http://$HOST_IP:$HTTP_PORT/static/|g\"  /home/taiga/taiga-back/settings/local.py
sed -i \"s|http://localhost/media/|http://$HOST_IP:$HTTP_PORT/media/|g\" /home/taiga/taiga-back/settings/local.py

# Edit conf files for frontend
sed -i \"s|circles.threefold.me|$HOST_IP:$HTTP_PORT|g\" /home/taiga/taiga-front-dist/dist/conf.json

if [ \"$HTTPS_FLAG\" = \"True\" ] || [ \"$HTTPS_FLAG\" = \"true\" ] ; then
    sed -i \"s|circles.threefold.me|$HOST_IP:$HTTP_PORT|g\" /home/taiga/taiga-front-dist/dist/conf.json
else
    sed -i \"s|https://circles.threefold.me|http://$HOST_IP:$HTTP_PORT|g\" /home/taiga/taiga-front-dist/dist/conf.json
    sed -i \"s|wss://circles.threefold.me|ws://$HOST_IP:$HTTP_PORT|g\" /home/taiga/taiga-front-dist/dist/conf.json
fi

/home/taiga/taiga-front-dist/dist/conf.json
sed -i \"s/listen 80 default_server/listen $HTTP_PORT default_server/g\" /etc/nginx/conf.d/taiga.conf


# Edit config.json for events
sed -i \"s/guest:guest/taiga:$SECRET_KEY/g\" /home/taiga/taiga-events/config.json
sed -i \"s/mysecret/$SECRET_KEY/g\" /home/taiga/taiga-events/config.json


service nginx start

# start startup script and start it
"""

[startup.taigaBack]
name = "bash"
after = ["setup"]
protected = true

[startup.taigaBack.args]
script = """
set -x
su taiga -c 'cd /home/taiga/taiga-back ; /home/taiga/taiga-back/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi'
"""

[startup.taigaEvents]
name = "bash"
after = ["setup"]
protected = true

[startup.taigaEvents.args]

script = """
set -x
su taiga -c 'cd /home/taiga/taiga-events ; /home/taiga/taiga-events/node_modules/coffeescript/bin/coffee /home/taiga/taiga-events/index.coffee'
"""